name: R7RS Tests

on: [push]

jobs:
  r7rs-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install ck
      run: sudo apt-get install libck-dev make git
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: Clone R7RS Tests
      run: |
        git clone https://github.com/ashinn/chibi-scheme --depth=1
        git -C chibi-scheme checkout 97faa0bf2d123c558d7ab79216906567c44cb03c
    - name: Clone (srfi 64)
      run: |
        git clone https://github.com/srfi-explorations/r7rs-srfi.git --depth=1
        mkdir -p chibi-scheme/tests/srfi
        cp r7rs-srfi/srfi/64.sld chibi-scheme/tests/srfi/
        cp r7rs-srfi/srfi/64.scm chibi-scheme/tests/srfi/
    - name: Fix r7rs-tests to use (srfi 64)
      run: |
        sed -i 's/(chibi test)/(srfi 64)/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '10 s/^/(define test test-equal)/' chibi-scheme/tests/r7rs-tests.scm
    - name: Remove (scheme r5rs) from imports
      run: |
        sed -i 's/(scheme r5rs)//' chibi-scheme/tests/r7rs-tests.scm
    - name: Comment out noncompiling tests
      run: |
        sed -i '413 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '477 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '482 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '485 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '491 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '493 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '557 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '595 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '633 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '658 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '760 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '761 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '783 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '784 s/^/;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '789 s/^/;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '903 s/^/;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '973 s/^/;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1806 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1808 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1811 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1813 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1815 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1944 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1948 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1950 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '1952 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '2076 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '2510 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '2268 s/^/;/' chibi-scheme/tests/r7rs-tests.scm
    - name: Comment out tests that use (chibi test) features
      run: |
        sed -i '917 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '918 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '919 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '920 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '921 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '922 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '923 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '924 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
        sed -i '925 s/^/#;/' chibi-scheme/tests/r7rs-tests.scm
    - name: Compile and run R7RS Tests
      run: |
        cd chibi-scheme/tests && cyclone -I . r7rs-tests.scm && ls && ./r7rs-tests.scm
