name: R7RS Tests

on: [push]

jobs:
  r7rs-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install ck
      run: sudo apt-get install libck-dev make git
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: Clone R7RS Tests
      run: git clone https://github.com/ashinn/chibi-scheme --depth=1
    - name: Fix the tests to use (srfi 64)
      run: sed -i 's/(chibi test)/(srfi 64)/' chibi-scheme/tests/r7rs-tests.scm
    - name: Compile R7RS Tests
      run: cyclone chibi-scheme/tests/r7rs-tests.scm
